import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { DarkModeProvider } from "@/context/DarkModeProvider";
import LayoutHandler from "./LayoutHandler";
import Providers from "./providers";


const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], // matches your import
});


export const metadata: Metadata = {
  title: "Bagel",
  description: "Generated by create next app",
    icons: {
    icon: "/login/logo-icon.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={`min-h-screen flex flex-col ${montserrat.variable} antialiased bg-[#111111]`}
      >
        <Providers>
          <DarkModeProvider>
            <LayoutHandler>{children}</LayoutHandler>
          </DarkModeProvider>
        </Providers>
      </body>
    </html>
  );
}