import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"], weight: ["400", "500", "600", "700"] });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Env0 Lite",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`h-screen flex flex-col ${geistSans.variable} ${geistMono.variable} ${inter.className} antialiased`}
      >
        <div className={`flex h-fit w-screen ${inter.className} bg-[#111111]`}>
              <div className="p-3 flex items-stretch justify-center h-fit">
                <div className="flex items-center justify-center flex-1">
                  <Image src="/login/Logo.svg" alt="Logo" width={30} height={35} priority /></div>
                <div className="flex items-center justify-center flex-1 ">
                  <span className="ml-3">TerraFuel</span>
                </div>
              </div>
            </div>
        {children}
      </body>
    </html>
  );
}
